# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# https://github.com/mmistakes/minimal-mistakes-algolia-search/blob/master/_config.yml

# Configurations
title: Michel Metran
masthead_title: "Michel Metran"
subtitle: "<i>DevOps</i>, <i>data science</i> e <i>data engineer</i>" # Opcional
# title_separator: "|" # Opcional

name: "Michel Metran"
email: michelmetran@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
repository: "michelmetran/michelmetran.github.io"
logo: "/assets/images/logo/logo.png"
#url: "https://michelmetran.com.br"

# Social Sharing
twitter_username: michelmetran
github_username: michelmetran
facebook:
  username: michelmetran

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin
minimal_mistakes_skin: air # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
layout: splash

# Search
search: true
search_provider: "algolia"
algolia:
  application_id: "6BW3PXB7TY"
  index_name: "mysite"
  search_only_api_key: "66be9231011a4a559c96383fd6563e6e"
  powered_by: true
  # files_to_exclude:
google:
  search_engine_id: d4e7b7ef17cde45fa

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0

# SEO Related
google_site_verification: M4srWgAFRkzg2rpTIT2aB2w7H_AoXpbMA_GMO1K4Pbc
bing_site_verification: c864d355156fc33422a30f66acd5805d
# yandex_site_verification:
# naver_site_verification
# baidu_site_verification

# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: "America/Sao_Paulo"
locale: pt-BR

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-Z5ZC58R3DX"
    anonymize_ip: false # default

# Posts
date_format: "%d.%m.%Y"
words_per_minute: 200

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Comments
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#comments
comments:
  provider: "disqus"
  disqus:
    shortname: "michelmetran"
  discourse:
    server: # meta.discourse.org

# Outputting
permalink: /posts/:title/ # /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-archives
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-algolia

# Autor
author: Michel Metran

# Rodap√©
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/michelmetran"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/michelmetran"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/michelmetran"

# Collections
collections_dir: collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  projetos:
    output: true
    permalink: /:collection/:path/
  trips:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: tag
    values:
      #author_profile: false
      comments: false
  - scope:
      path: ""
      type: category
    values:
      comments: false
  # Posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true

  # Collections: Pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      #related: true
      #toc: true
      #toc_sticky: true

  # Collections: Portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

  # Collections: Trips
  - scope:
      path: ""
      type: trips
    values:
      layout: single
      author_profile: false
      share: true

  # Collections: Projetos
  - scope:
      path: ""
      type: projetos
    values:
      layout: single
      author_profile: false
      share: true
      comment: true

# Archives
category_archive:
  type: jekyll-archives # type: liquid
  path: /posts/categories/ # /categories/

tag_archive:
  type: jekyll-archives # type: liquid
  path: /posts/tags/ # /tags/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /posts/categories/:name/
    tag: /posts/tags/:name/

# Scripts
# head_scripts:
#   - https://code.jquery.com/jquery-3.3.1.min.js
#footer_scripts:
#  - /assets/js/your-custom-footer-script.js
#after_footer_scripts:
#  - /assets/js/custom-script-loads-after-footer.js

# Adiciona Possibilitade de Copiar Code Blocks
# https://github.com/mmistakes/minimal-mistakes/discussions/2795
after_footer_scripts:
  - https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
  - /assets/js/clipboardrouge.js
